### ISSUE TITLE
I find resize a better result for the collage

### ISSUE THREAD

**Issue by vkyeswa** [tzsk/collage#203] opened 2023-01-21 08:09 UTC
Current Implementation (One Image Processing)
`/**
     * Process Image.
     */
    protected function process()
    {
        $width = $this->file->getWidth() - $this->file->getPadding();
        $height = $this->file->getHeight() - $this->file->getPadding();

        $this->images = collect([$this->images->first()->fit($width, $height)]);
    }`

I found that handling this using **resize** instead of **fit** gives me the entire image on the canvas, with the aspect ratio maintained of course.
`/**
     * Process Image.
     */
    protected function process()
    {
        $width = $this->file->getWidth() - $this->file->getPadding();
        $height = $this->file->getHeight() - $this->file->getPadding();

        $this->images = collect([$this->images->first()->resize($width, $height,function ($constraint) {
            $constraint->aspectRatio();
        })]);
    }`

Let me know what you think of this, I currently tried it with the OneImage and TwoImage classes

**Comment by tzsk** [comment] 2023-01-21 13:20
I would like to see the results along with the. original images.

What I know is, that `resize` will squeeze/stretch the image into the final size. Which leads to distortion. I might be wrong.

**Comment by vkyeswa** [comment] 2023-01-21 14:22
That's why the `$constraint->aspectRatio();` is required

**Comment by tzsk** [comment] 2023-01-21 18:07
That would lead to white patches on the top & bottom if the image is wider, and on the sides if it's taller.

Put some examples with that here so we can look at it.

**Comment by vkyeswa** [comment] 2023-01-21 18:52
Based on the codes I shared earlier
**These are the two test images**
![testImage1](https://user-images.githubusercontent.com/5016129/213882312-aab69ecf-4c4b-4517-88ae-79078846dd83.png)
**Test Image 1**

![testImage2](https://user-images.githubusercontent.com/5016129/213882320-b6fcd5ca-164f-4a30-8c03-2b30420099d6.png)
**Test Image 2**

**Making a collage of the 2**
![using-fit](https://user-images.githubusercontent.com/5016129/213882270-51d94e34-d2cf-426b-a9bf-d699ba3ef82b.jpg)
**Using "fit"**

![usingresize](https://user-images.githubusercontent.com/5016129/213882358-c5a0c40d-badf-412e-8a00-063d900a725d.jpg)
**Using "resize"**

I find resize desirable when I need the entire image to be on the collage and not cropped out, it can be an option on the Collage class if you want to use fit or resize depending on the collage you want to make.

**Comment by tzsk** [comment] 2023-01-21 20:07
Unfortunately I was right. But I'm sorry to say the symmetrical 'fit' is more desirable to me.

You're welcome to override the generators by extending them with custom implementation.

But for the most folks, in terms of design and aesthetics the symmetrical holds up pretty good as a default.

Closing this as it's not an issue but the default intended behaviour.

**Closed by tzsk** 2023-01-21 20:07 UTC
